### ISSUE TITLE
Multipart/form-data support

### ISSUE THREAD

**Issue by polykoi** [infinum/dox#38]
I run into an issue with generating documentation for next test case:
```
describe 'Success' do
  let(:headers) { { Authorization: 'auth token' } }
  let(:params) { { image: fixture_file_upload('files/image.jpeg', 'image/jpg') } }

  before do
    put '/api/v1/company/logo', params: params, headers: headers
  end

  it 'renders with updated image' do
    expect(response).to be_ok
    expect(response).to match_json_schema('image/update')
  end
end
```
My config in `rails_helper.rb`:
```
require 'dox'

...

Dox.configure do |config|
  config.header_file_path = Rails.root.join('spec', 'api_doc', 'v1', 'descriptions', 'header.md')
  config.desc_folder_path = Rails.root.join('spec', 'api_doc', 'v1', 'descriptions')
  config.headers_whitelist = ['Accept', 'X-Refresh-Token']
end

config.after(:each, :dox) do |example|
  example.metadata[:request] = request
  example.metadata[:response] = response
end
```
The error trace:
```
Traceback (most recent call last):
         6: from /Users/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dox-1.1.0/lib/dox/printers/action_printer.rb:9:in `print'
         5: from /Users/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dox-1.1.0/lib/dox/printers/action_printer.rb:9:in `each'
         4: from /Users/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dox-1.1.0/lib/dox/printers/action_printer.rb:10:in `block in print'
         3: from /Users/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dox-1.1.0/lib/dox/printers/example_printer.rb:8:in `print'
         2: from /Users/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dox-1.1.0/lib/dox/printers/example_printer.rb:21:in `print_example_request'
         1: from /Users/user/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dox-1.1.0/lib/dox/printers/example_printer.rb:21:in `puts'
/Users/alexandr/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/dox-1.1.0/lib/dox/printers/example_printer.rb:21:in `write': "\xFF" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

As it can be seen while debugging it stumbles upon raw image data in request's body.

**Comment by polykoi** [comment]
I've written a dirty hack as temporary workaround, sharing it in case anyone will have same problem
```
config.after(:each, :dox) do |example|
  example.metadata[:request] = if request.headers['CONTENT_TYPE']&.start_with?('multipart/form-data; boundary=')
    patched_request = request.dup
    def patched_request.body
      OpenStruct.new(read: request_parameters.to_json)
    end
    patched_request
  else
    request
  end

  example.metadata[:response] = response
end
```

**Comment by cilim** [comment]
Hi @polykoi 👋 

This should be fixed in the latest version of dox (1.1.0)

As I see in the `Dox::Printers::ExamplePrinter` it's checking the content_type of the request before printing out the request body:

```
def formatted_body(body_str, content_type)
  case content_type
  when %r{application\/.*json}
    pretty_json(safe_json_parse(body_str))
  when /xml/
    pretty_xml(body_str)
  else
    body_str
  end
end
```

Which version are you using?

**Comment by polykoi** [comment]
Hi @cilim
```
group :test do
  gem 'dox', require: false
end
```
in gemfile resulted in 
```
dox (1.1.0)
```

**Comment by cilim** [comment]
Hi again @polykoi 👋 

Sorry for the wait, but the PR to support multipart/form-data formatting is opened.

I managed to reproduce your issue and fix it locally:

```
describe 'test dox' do
  include Docs::Api::V1::Checks::Update

  let(:headers) do
    {
      'Authorization' => 'auth token',
      'Content-Type' => 'multipart/form-data; boundary='
    }
  end
  let(:params) do
    { status: :uploaded, image: fixture_file_upload('images/aws_s3_example_id', 'image/jpg') }
  end

  it 'returns 200 status', :dox do
    put 'checks', params: params, headers: headers
    expect(response).to have_http_status(:ok)
  end
end
```

We'll make a new release of the gem soon and you can update it and get rid of the hack :)

**Comment by cilim** [comment]
@polykoi dox version [1.2.0](https://rubygems.org/gems/dox/versions/1.2.0) is now available.

1.2.0 supports multipart/form-data requests.

Cheers!
