### ISSUE TITLE
Uninitialized constant Dox::Formatter::Forwardable

### ISSUE THREAD

**Issue by Rafix02** [infinum/dox#43]
When I run `rspec -f Dox::Formatter` I get:

```
Traceback (most recent call last):
        17: from /usr/local/bundle/bin/rspec:23:in `<main>'
        16: from /usr/local/bundle/bin/rspec:23:in `load'
        15: from /usr/local/bundle/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
        14: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
        13: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
        12: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
        11: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
        10: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:23:in `configure'
         9: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `load_formatters_into'
         8: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `each'
         7: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `block in load_formatters_into'
         6: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:878:in `add_formatter'
         5: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:146:in `add'
         4: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:177:in `find_formatter'
         3: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:225:in `custom_formatter'
         2: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:225:in `inject'
         1: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:225:in `each'
/usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:225:in `block in custom_formatter': uninitialized constant Dox (NameError)
        17: from /usr/local/bundle/bin/rspec:23:in `<main>'
        16: from /usr/local/bundle/bin/rspec:23:in `load'
        15: from /usr/local/bundle/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
        14: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
        13: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
        12: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
        11: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
        10: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:23:in `configure'
         9: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `load_formatters_into'
         8: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `each'
         7: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `block in load_formatters_into'
         6: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:878:in `add_formatter'
         5: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:146:in `add'
         4: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:177:in `find_formatter'
         3: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:224:in `custom_formatter'
         2: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:227:in `rescue in custom_formatter'
         1: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dox/formatter (LoadError)
        21: from /usr/local/bundle/bin/rspec:23:in `<main>'
        20: from /usr/local/bundle/bin/rspec:23:in `load'
        19: from /usr/local/bundle/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
        18: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
        17: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
        16: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
        15: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
        14: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:23:in `configure'
        13: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `load_formatters_into'
        12: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `each'
        11: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:117:in `block in load_formatters_into'
        10: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:878:in `add_formatter'
         9: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:146:in `add'
         8: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:177:in `find_formatter'
         7: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:224:in `custom_formatter'
         6: from /usr/local/bundle/gems/rspec-core-3.7.1/lib/rspec/core/formatters.rb:227:in `rescue in custom_formatter'
         5: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         4: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
         3: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
         2: from /usr/local/bundle/gems/dox-1.1.0/lib/dox/formatter.rb:5:in `<top (required)>'
         1: from /usr/local/bundle/gems/dox-1.1.0/lib/dox/formatter.rb:6:in `<module:Dox>'
/usr/local/bundle/gems/dox-1.1.0/lib/dox/formatter.rb:7:in `<class:Formatter>': uninitialized constant Dox::Formatter::Forwardable (NameError)
```

I have this in `rails_helper.rb`:

```
RSpec.configure do |config|
  config.include FeatureMacros

  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!

  config.after(:each, :dox) do |example|
    example.metadata[:request] = request
    example.metadata[:response] = response
  end
end

Dox.configure do |config|
  config.header_file_path = Rails.root.join('spec/docs/v2/descriptions/header.md')
  config.desc_folder_path = Rails.root.join('spec/docs/v2/descriptions')
  config.headers_whitelist = %w[Email Password Password-Confirmation
                                Ahoy-Visit Ahoy-Visitor Access-Token
                                Token-Type Client Expiry UID Profile-ID
                                Birth-date Reg-Number Document]
end
```

Editing the gem folder and adding ```require 'forwardable'``` in `lib/dox/formatter.rb` seems to solve the problem.

**Comment by nelsonmfinda** [comment]
I have the same problem. Miss @melcha , can you help us?

**Comment by melcha** [comment]
@nelsonmfinda, @Rafix02 which Ruby version and Rails version are you using?

**Comment by nelsonmfinda** [comment]
Ruby: 2.6.0
Rails: 5.2.3

I solved this problem following the solution related by @Rafix02. @melcha I want to contribute solving this issue.

**Comment by Rafix02** [comment]
@melcha I'm using Rails 5.2.3 like @nelsonmfinda.

To check if it was a Ruby 2.6 problem I also tried versions 2.3.8 and 2.5.5, but got the same results. :thinking:

**Comment by melcha** [comment]
@Rafix02, @nelsonmfinda 

We've managed to reproduce this same issue with **Ruby 2.6 / Rails 5.2.3 / rspec-rails 3.7.1**
We've experienced similar, only worse, issue with **Ruby 2.6 / Rails 5.2.3 / rspec-rails 3.8.2**,  where none of the dox's internal classes were initialized (Dox::Printers::DocumentPrinter, Dox::Printers::BasePrinter, ...)

Adding `--require rails_helper` to the `.rspec` file fixed the issue in both cases. It seems the dox was not loaded at all (because we require it in the rails_helper). 

**forwardable** module is already required in the root **dox** module.

**Comment by Rafix02** [comment]
@melcha I see. I tried adding `config.add_formatter Dox::Formatter` to the `RSpec.configure` section of the rails_helper and it didn't complain either (rspec-rails 3.7.2). So apparently it's a new rspec/rspec-rails behaviour/bug with the `--format` flag?

Is running with `--require rails_helper` gonna be the official solution? If so, or even if just a workaround, I guess it'd be a good idea to add that info to the README, right? I could open a PR if you agree.

**Comment by melcha** [comment]
@Rafix02, it would seem so.

Yes, we should add a note about `--require rails_helper` to the README. Feel free to open a PR 🙂
